//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:03:55 PM CST 
//


package org.oagis.model.v101;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for requesting additional documents be sent along with ordered item
 * 
 * <p>Java class for AdditionalDocumentRequestBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalDocumentRequestBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}IdentificationType">
 *       &lt;sequence>
 *         &lt;element name="DocumentIdentification" type="{http://www.openapplications.org/oagis/10}DocumentIdentificationType" minOccurs="0"/>
 *         &lt;element name="RecipientParty" type="{http://www.openapplications.org/oagis/10}PartyType" minOccurs="0"/>
 *         &lt;element name="OriginalQuantity" type="{http://www.openapplications.org/oagis/10}OpenQuantityType" minOccurs="0"/>
 *         &lt;element name="CopiesNumber" type="{http://www.openapplications.org/oagis/10}NumberType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalDocumentRequestBaseType", propOrder = {
    "documentIdentification",
    "recipientParty",
    "originalQuantity",
    "copiesNumber"
})
@XmlSeeAlso({
    AdditionalDocumentRequestType.class
})
public class AdditionalDocumentRequestBaseType
    extends IdentificationType
{

    @XmlElement(name = "DocumentIdentification")
    protected DocumentIdentificationType documentIdentification;
    @XmlElement(name = "RecipientParty")
    protected PartyType recipientParty;
    @XmlElement(name = "OriginalQuantity")
    protected OpenQuantityType originalQuantity;
    @XmlElement(name = "CopiesNumber")
    protected BigDecimal copiesNumber;

    /**
     * Gets the value of the documentIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentIdentificationType }
     *     
     */
    public DocumentIdentificationType getDocumentIdentification() {
        return documentIdentification;
    }

    /**
     * Sets the value of the documentIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentIdentificationType }
     *     
     */
    public void setDocumentIdentification(DocumentIdentificationType value) {
        this.documentIdentification = value;
    }

    /**
     * Gets the value of the recipientParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getRecipientParty() {
        return recipientParty;
    }

    /**
     * Sets the value of the recipientParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setRecipientParty(PartyType value) {
        this.recipientParty = value;
    }

    /**
     * Gets the value of the originalQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link OpenQuantityType }
     *     
     */
    public OpenQuantityType getOriginalQuantity() {
        return originalQuantity;
    }

    /**
     * Sets the value of the originalQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenQuantityType }
     *     
     */
    public void setOriginalQuantity(OpenQuantityType value) {
        this.originalQuantity = value;
    }

    /**
     * Gets the value of the copiesNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCopiesNumber() {
        return copiesNumber;
    }

    /**
     * Sets the value of the copiesNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCopiesNumber(BigDecimal value) {
        this.copiesNumber = value;
    }

}
