//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 04:57:33 PM CST 
//


package org.oagis.model.v101;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllocateResourceDetailBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllocateResourceDetailBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}LineBaseType">
 *       &lt;sequence>
 *         &lt;element name="WorkCenterID" type="{http://www.openapplications.org/oagis/10}IDType" minOccurs="0"/>
 *         &lt;element name="AllocateResources" type="{http://www.openapplications.org/oagis/10}AllocateResourcesType" minOccurs="0"/>
 *         &lt;element name="Party" type="{http://www.openapplications.org/oagis/10}PartyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllocateResourceDetailBaseType", propOrder = {
    "workCenterID",
    "allocateResources",
    "party"
})
@XmlSeeAlso({
    AllocateResourceDetailType.class
})
public class AllocateResourceDetailBaseType
    extends LineBaseType
{

    @XmlElement(name = "WorkCenterID")
    protected IDType workCenterID;
    @XmlElement(name = "AllocateResources")
    protected AllocateResourcesType allocateResources;
    @XmlElement(name = "Party")
    protected List<PartyType> party;

    /**
     * Gets the value of the workCenterID property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getWorkCenterID() {
        return workCenterID;
    }

    /**
     * Sets the value of the workCenterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setWorkCenterID(IDType value) {
        this.workCenterID = value;
    }

    /**
     * Gets the value of the allocateResources property.
     * 
     * @return
     *     possible object is
     *     {@link AllocateResourcesType }
     *     
     */
    public AllocateResourcesType getAllocateResources() {
        return allocateResources;
    }

    /**
     * Sets the value of the allocateResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllocateResourcesType }
     *     
     */
    public void setAllocateResources(AllocateResourcesType value) {
        this.allocateResources = value;
    }

    /**
     * Gets the value of the party property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the party property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType }
     * 
     * 
     */
    public List<PartyType> getParty() {
        if (party == null) {
            party = new ArrayList<PartyType>();
        }
        return this.party;
    }

}
