//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 04:57:37 PM CST 
//


package org.oagis.model.v101;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * The type that represents a specific, identifiable sub-set of a product that represents the result from a specific formula and process
 * 
 * <p>Java class for BatchBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatchBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}ItemInstanceIdentificationBaseType">
 *       &lt;sequence>
 *         &lt;element name="Container" type="{http://www.openapplications.org/oagis/10}ContainerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Party" type="{http://www.openapplications.org/oagis/10}PartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ManufacturingParty" type="{http://www.openapplications.org/oagis/10}PartyType" minOccurs="0"/>
 *         &lt;element name="ManufactureDateTime" type="{http://www.openapplications.org/oagis/10}DateTimeType" minOccurs="0"/>
 *         &lt;element name="ExpiriationDateTime" type="{http://www.openapplications.org/oagis/10}DateTimeType" minOccurs="0"/>
 *         &lt;element name="HazardousMaterialCodes" type="{http://www.openapplications.org/oagis/10}CodesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchBaseType", propOrder = {
    "container",
    "party",
    "manufacturingParty",
    "manufactureDateTime",
    "expiriationDateTime",
    "hazardousMaterialCodes"
})
@XmlSeeAlso({
    BatchType.class
})
public class BatchBaseType
    extends ItemInstanceIdentificationBaseType
{

    @XmlElement(name = "Container")
    protected List<ContainerType> container;
    @XmlElement(name = "Party")
    protected List<PartyType> party;
    @XmlElement(name = "ManufacturingParty")
    protected PartyType manufacturingParty;
    @XmlElement(name = "ManufactureDateTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String manufactureDateTime;
    @XmlElement(name = "ExpiriationDateTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String expiriationDateTime;
    @XmlElement(name = "HazardousMaterialCodes")
    protected List<CodesType> hazardousMaterialCodes;

    /**
     * Gets the value of the container property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the container property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContainerType }
     * 
     * 
     */
    public List<ContainerType> getContainer() {
        if (container == null) {
            container = new ArrayList<ContainerType>();
        }
        return this.container;
    }

    /**
     * Gets the value of the party property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the party property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType }
     * 
     * 
     */
    public List<PartyType> getParty() {
        if (party == null) {
            party = new ArrayList<PartyType>();
        }
        return this.party;
    }

    /**
     * Gets the value of the manufacturingParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getManufacturingParty() {
        return manufacturingParty;
    }

    /**
     * Sets the value of the manufacturingParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setManufacturingParty(PartyType value) {
        this.manufacturingParty = value;
    }

    /**
     * Gets the value of the manufactureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufactureDateTime() {
        return manufactureDateTime;
    }

    /**
     * Sets the value of the manufactureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufactureDateTime(String value) {
        this.manufactureDateTime = value;
    }

    /**
     * Gets the value of the expiriationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiriationDateTime() {
        return expiriationDateTime;
    }

    /**
     * Sets the value of the expiriationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiriationDateTime(String value) {
        this.expiriationDateTime = value;
    }

    /**
     * Gets the value of the hazardousMaterialCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hazardousMaterialCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHazardousMaterialCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodesType }
     * 
     * 
     */
    public List<CodesType> getHazardousMaterialCodes() {
        if (hazardousMaterialCodes == null) {
            hazardousMaterialCodes = new ArrayList<CodesType>();
        }
        return this.hazardousMaterialCodes;
    }

}
