//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:01:20 PM CST 
//


package org.oagis.model.v101;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ProductionOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductionOrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductionOrderHeader" type="{http://www.openapplications.org/oagis/10}ProductionOrderHeaderType" minOccurs="0"/>
 *         &lt;element name="ProductionOrderLine" type="{http://www.openapplications.org/oagis/10}ProductionOrderLineType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ComponentItemInstance" type="{http://www.openapplications.org/oagis/10}ItemInstanceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Operation" type="{http://www.openapplications.org/oagis/10}OperationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Extension" type="{http://www.openapplications.org/oagis/10}ProductionOrderExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typeCode" type="{http://www.openapplications.org/oagis/10}CodeType_1E7368" />
 *       &lt;attribute name="actionCode" type="{http://www.openapplications.org/oagis/10}ActionCodeContentType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductionOrderType", propOrder = {
    "productionOrderHeader",
    "productionOrderLine",
    "componentItemInstance",
    "operation",
    "extension"
})
public class ProductionOrderType {

    @XmlElement(name = "ProductionOrderHeader")
    protected ProductionOrderHeaderType productionOrderHeader;
    @XmlElement(name = "ProductionOrderLine")
    protected List<ProductionOrderLineType> productionOrderLine;
    @XmlElement(name = "ComponentItemInstance")
    protected List<ItemInstanceType> componentItemInstance;
    @XmlElement(name = "Operation")
    protected List<OperationType> operation;
    @XmlElement(name = "Extension")
    protected List<ProductionOrderExtensionType> extension;
    @XmlAttribute(name = "typeCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeCode;
    @XmlAttribute(name = "actionCode")
    protected String actionCode;

    /**
     * Gets the value of the productionOrderHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ProductionOrderHeaderType }
     *     
     */
    public ProductionOrderHeaderType getProductionOrderHeader() {
        return productionOrderHeader;
    }

    /**
     * Sets the value of the productionOrderHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductionOrderHeaderType }
     *     
     */
    public void setProductionOrderHeader(ProductionOrderHeaderType value) {
        this.productionOrderHeader = value;
    }

    /**
     * Gets the value of the productionOrderLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productionOrderLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductionOrderLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductionOrderLineType }
     * 
     * 
     */
    public List<ProductionOrderLineType> getProductionOrderLine() {
        if (productionOrderLine == null) {
            productionOrderLine = new ArrayList<ProductionOrderLineType>();
        }
        return this.productionOrderLine;
    }

    /**
     * Gets the value of the componentItemInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the componentItemInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponentItemInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemInstanceType }
     * 
     * 
     */
    public List<ItemInstanceType> getComponentItemInstance() {
        if (componentItemInstance == null) {
            componentItemInstance = new ArrayList<ItemInstanceType>();
        }
        return this.componentItemInstance;
    }

    /**
     * Gets the value of the operation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationType }
     * 
     * 
     */
    public List<OperationType> getOperation() {
        if (operation == null) {
            operation = new ArrayList<OperationType>();
        }
        return this.operation;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductionOrderExtensionType }
     * 
     * 
     */
    public List<ProductionOrderExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ProductionOrderExtensionType>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the actionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionCode() {
        return actionCode;
    }

    /**
     * Sets the value of the actionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionCode(String value) {
        this.actionCode = value;
    }

}
