//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:01:20 PM CST 
//


package org.oagis.model.v101;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductionOrderLineBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductionOrderLineBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}StatusLineBaseType">
 *       &lt;sequence>
 *         &lt;element name="BOMReference" type="{http://www.openapplications.org/oagis/10}BOMReferenceType" minOccurs="0"/>
 *         &lt;element name="ManufacturingItem" type="{http://www.openapplications.org/oagis/10}ManufacturingItemType" minOccurs="0"/>
 *         &lt;element name="ManufacturingItemInstance" type="{http://www.openapplications.org/oagis/10}ItemInstanceType" minOccurs="0"/>
 *         &lt;element name="SiteLocation" type="{http://www.openapplications.org/oagis/10}LocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OrderQuantity" type="{http://www.openapplications.org/oagis/10}QuantityType" minOccurs="0"/>
 *         &lt;element name="ProducedQuantity" type="{http://www.openapplications.org/oagis/10}QuantityType" minOccurs="0"/>
 *         &lt;element name="TrackingIndicator" type="{http://www.openapplications.org/oagis/10}IndicatorType" minOccurs="0"/>
 *         &lt;element name="SerialLot" type="{http://www.openapplications.org/oagis/10}SerialLotType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Distribution" type="{http://www.openapplications.org/oagis/10}DistributionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExecutionTimePeriod" type="{http://www.openapplications.org/oagis/10}TimePeriodType" minOccurs="0"/>
 *         &lt;element name="ForecastedTimePeriod" type="{http://www.openapplications.org/oagis/10}TimePeriodType" minOccurs="0"/>
 *         &lt;element name="NeedDeliveryDate" type="{http://www.openapplications.org/oagis/10}DateTimeType" minOccurs="0"/>
 *         &lt;element name="DueDateTime" type="{http://www.openapplications.org/oagis/10}DateTimeType" minOccurs="0"/>
 *         &lt;element name="RequiredDateTime" type="{http://www.openapplications.org/oagis/10}DateTimeType" minOccurs="0"/>
 *         &lt;element name="AvailableDateTime" type="{http://www.openapplications.org/oagis/10}DateTimeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductionOrderLineBaseType", propOrder = {
    "bomReference",
    "manufacturingItem",
    "manufacturingItemInstance",
    "siteLocation",
    "orderQuantity",
    "producedQuantity",
    "trackingIndicator",
    "serialLot",
    "distribution",
    "executionTimePeriod",
    "forecastedTimePeriod",
    "needDeliveryDate",
    "dueDateTime",
    "requiredDateTime",
    "availableDateTime"
})
@XmlSeeAlso({
    ProductionOrderLineType.class
})
public class ProductionOrderLineBaseType
    extends StatusLineBaseType
{

    @XmlElement(name = "BOMReference")
    protected BOMReferenceType bomReference;
    @XmlElement(name = "ManufacturingItem")
    protected ManufacturingItemType manufacturingItem;
    @XmlElement(name = "ManufacturingItemInstance")
    protected ItemInstanceType manufacturingItemInstance;
    @XmlElement(name = "SiteLocation")
    protected List<LocationType> siteLocation;
    @XmlElement(name = "OrderQuantity")
    protected QuantityType orderQuantity;
    @XmlElement(name = "ProducedQuantity")
    protected QuantityType producedQuantity;
    @XmlElement(name = "TrackingIndicator")
    protected Boolean trackingIndicator;
    @XmlElement(name = "SerialLot")
    protected List<SerialLotType> serialLot;
    @XmlElement(name = "Distribution")
    protected List<DistributionType> distribution;
    @XmlElement(name = "ExecutionTimePeriod")
    protected TimePeriodType executionTimePeriod;
    @XmlElement(name = "ForecastedTimePeriod")
    protected TimePeriodType forecastedTimePeriod;
    @XmlElement(name = "NeedDeliveryDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String needDeliveryDate;
    @XmlElement(name = "DueDateTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String dueDateTime;
    @XmlElement(name = "RequiredDateTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String requiredDateTime;
    @XmlElement(name = "AvailableDateTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String availableDateTime;

    /**
     * Gets the value of the bomReference property.
     * 
     * @return
     *     possible object is
     *     {@link BOMReferenceType }
     *     
     */
    public BOMReferenceType getBOMReference() {
        return bomReference;
    }

    /**
     * Sets the value of the bomReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link BOMReferenceType }
     *     
     */
    public void setBOMReference(BOMReferenceType value) {
        this.bomReference = value;
    }

    /**
     * Gets the value of the manufacturingItem property.
     * 
     * @return
     *     possible object is
     *     {@link ManufacturingItemType }
     *     
     */
    public ManufacturingItemType getManufacturingItem() {
        return manufacturingItem;
    }

    /**
     * Sets the value of the manufacturingItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManufacturingItemType }
     *     
     */
    public void setManufacturingItem(ManufacturingItemType value) {
        this.manufacturingItem = value;
    }

    /**
     * Gets the value of the manufacturingItemInstance property.
     * 
     * @return
     *     possible object is
     *     {@link ItemInstanceType }
     *     
     */
    public ItemInstanceType getManufacturingItemInstance() {
        return manufacturingItemInstance;
    }

    /**
     * Sets the value of the manufacturingItemInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemInstanceType }
     *     
     */
    public void setManufacturingItemInstance(ItemInstanceType value) {
        this.manufacturingItemInstance = value;
    }

    /**
     * Gets the value of the siteLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the siteLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSiteLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationType }
     * 
     * 
     */
    public List<LocationType> getSiteLocation() {
        if (siteLocation == null) {
            siteLocation = new ArrayList<LocationType>();
        }
        return this.siteLocation;
    }

    /**
     * Gets the value of the orderQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getOrderQuantity() {
        return orderQuantity;
    }

    /**
     * Sets the value of the orderQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setOrderQuantity(QuantityType value) {
        this.orderQuantity = value;
    }

    /**
     * Gets the value of the producedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getProducedQuantity() {
        return producedQuantity;
    }

    /**
     * Sets the value of the producedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setProducedQuantity(QuantityType value) {
        this.producedQuantity = value;
    }

    /**
     * Gets the value of the trackingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTrackingIndicator() {
        return trackingIndicator;
    }

    /**
     * Sets the value of the trackingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTrackingIndicator(Boolean value) {
        this.trackingIndicator = value;
    }

    /**
     * Gets the value of the serialLot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serialLot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSerialLot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SerialLotType }
     * 
     * 
     */
    public List<SerialLotType> getSerialLot() {
        if (serialLot == null) {
            serialLot = new ArrayList<SerialLotType>();
        }
        return this.serialLot;
    }

    /**
     * Gets the value of the distribution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distribution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistribution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DistributionType }
     * 
     * 
     */
    public List<DistributionType> getDistribution() {
        if (distribution == null) {
            distribution = new ArrayList<DistributionType>();
        }
        return this.distribution;
    }

    /**
     * Gets the value of the executionTimePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodType }
     *     
     */
    public TimePeriodType getExecutionTimePeriod() {
        return executionTimePeriod;
    }

    /**
     * Sets the value of the executionTimePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodType }
     *     
     */
    public void setExecutionTimePeriod(TimePeriodType value) {
        this.executionTimePeriod = value;
    }

    /**
     * Gets the value of the forecastedTimePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodType }
     *     
     */
    public TimePeriodType getForecastedTimePeriod() {
        return forecastedTimePeriod;
    }

    /**
     * Sets the value of the forecastedTimePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodType }
     *     
     */
    public void setForecastedTimePeriod(TimePeriodType value) {
        this.forecastedTimePeriod = value;
    }

    /**
     * Gets the value of the needDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeedDeliveryDate() {
        return needDeliveryDate;
    }

    /**
     * Sets the value of the needDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeedDeliveryDate(String value) {
        this.needDeliveryDate = value;
    }

    /**
     * Gets the value of the dueDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDateTime() {
        return dueDateTime;
    }

    /**
     * Sets the value of the dueDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDateTime(String value) {
        this.dueDateTime = value;
    }

    /**
     * Gets the value of the requiredDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiredDateTime() {
        return requiredDateTime;
    }

    /**
     * Sets the value of the requiredDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiredDateTime(String value) {
        this.requiredDateTime = value;
    }

    /**
     * Gets the value of the availableDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailableDateTime() {
        return availableDateTime;
    }

    /**
     * Sets the value of the availableDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailableDateTime(String value) {
        this.availableDateTime = value;
    }

}
