//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:03:41 PM CST 
//


package org.oagis.model.v101;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ControlProcessBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlProcessBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}RiskControlComponentBaseType">
 *       &lt;sequence>
 *         &lt;element name="OwnerParty" type="{http://www.openapplications.org/oagis/10}PartyType" minOccurs="0"/>
 *         &lt;element name="Party" type="{http://www.openapplications.org/oagis/10}PartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ApprovalStatus" type="{http://www.openapplications.org/oagis/10}StatusType" minOccurs="0"/>
 *         &lt;element name="SignificantProcessIndicator" type="{http://www.openapplications.org/oagis/10}IndicatorType" minOccurs="0"/>
 *         &lt;element name="StandardProcessIndicator" type="{http://www.openapplications.org/oagis/10}IndicatorType" minOccurs="0"/>
 *         &lt;element name="CategoryCodes" type="{http://www.openapplications.org/oagis/10}CodesType" minOccurs="0"/>
 *         &lt;element name="ParentProcessID" type="{http://www.openapplications.org/oagis/10}IDType" minOccurs="0"/>
 *         &lt;element name="ExposedRiskIDs" type="{http://www.openapplications.org/oagis/10}SequencedIDsType" minOccurs="0"/>
 *         &lt;element name="GeneralLedgerAccount" type="{http://www.openapplications.org/oagis/10}GeneralLedgerAccountType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OperationalMeasureIDs" type="{http://www.openapplications.org/oagis/10}SequencedIDsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlProcessBaseType", propOrder = {
    "ownerParty",
    "party",
    "approvalStatus",
    "significantProcessIndicator",
    "standardProcessIndicator",
    "categoryCodes",
    "parentProcessID",
    "exposedRiskIDs",
    "generalLedgerAccount",
    "operationalMeasureIDs"
})
@XmlSeeAlso({
    ControlProcessType.class
})
public class ControlProcessBaseType
    extends RiskControlComponentBaseType
{

    @XmlElement(name = "OwnerParty")
    protected PartyType ownerParty;
    @XmlElement(name = "Party")
    protected List<PartyType> party;
    @XmlElement(name = "ApprovalStatus")
    protected StatusType approvalStatus;
    @XmlElement(name = "SignificantProcessIndicator")
    protected Boolean significantProcessIndicator;
    @XmlElement(name = "StandardProcessIndicator")
    protected Boolean standardProcessIndicator;
    @XmlElement(name = "CategoryCodes")
    protected CodesType categoryCodes;
    @XmlElement(name = "ParentProcessID")
    protected IDType parentProcessID;
    @XmlElement(name = "ExposedRiskIDs")
    protected SequencedIDsType exposedRiskIDs;
    @XmlElement(name = "GeneralLedgerAccount")
    protected List<GeneralLedgerAccountType> generalLedgerAccount;
    @XmlElement(name = "OperationalMeasureIDs")
    protected SequencedIDsType operationalMeasureIDs;

    /**
     * Gets the value of the ownerParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getOwnerParty() {
        return ownerParty;
    }

    /**
     * Sets the value of the ownerParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setOwnerParty(PartyType value) {
        this.ownerParty = value;
    }

    /**
     * Gets the value of the party property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the party property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType }
     * 
     * 
     */
    public List<PartyType> getParty() {
        if (party == null) {
            party = new ArrayList<PartyType>();
        }
        return this.party;
    }

    /**
     * Gets the value of the approvalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * Sets the value of the approvalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setApprovalStatus(StatusType value) {
        this.approvalStatus = value;
    }

    /**
     * Gets the value of the significantProcessIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSignificantProcessIndicator() {
        return significantProcessIndicator;
    }

    /**
     * Sets the value of the significantProcessIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSignificantProcessIndicator(Boolean value) {
        this.significantProcessIndicator = value;
    }

    /**
     * Gets the value of the standardProcessIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStandardProcessIndicator() {
        return standardProcessIndicator;
    }

    /**
     * Sets the value of the standardProcessIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStandardProcessIndicator(Boolean value) {
        this.standardProcessIndicator = value;
    }

    /**
     * Gets the value of the categoryCodes property.
     * 
     * @return
     *     possible object is
     *     {@link CodesType }
     *     
     */
    public CodesType getCategoryCodes() {
        return categoryCodes;
    }

    /**
     * Sets the value of the categoryCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodesType }
     *     
     */
    public void setCategoryCodes(CodesType value) {
        this.categoryCodes = value;
    }

    /**
     * Gets the value of the parentProcessID property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getParentProcessID() {
        return parentProcessID;
    }

    /**
     * Sets the value of the parentProcessID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setParentProcessID(IDType value) {
        this.parentProcessID = value;
    }

    /**
     * Gets the value of the exposedRiskIDs property.
     * 
     * @return
     *     possible object is
     *     {@link SequencedIDsType }
     *     
     */
    public SequencedIDsType getExposedRiskIDs() {
        return exposedRiskIDs;
    }

    /**
     * Sets the value of the exposedRiskIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequencedIDsType }
     *     
     */
    public void setExposedRiskIDs(SequencedIDsType value) {
        this.exposedRiskIDs = value;
    }

    /**
     * Gets the value of the generalLedgerAccount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generalLedgerAccount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneralLedgerAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeneralLedgerAccountType }
     * 
     * 
     */
    public List<GeneralLedgerAccountType> getGeneralLedgerAccount() {
        if (generalLedgerAccount == null) {
            generalLedgerAccount = new ArrayList<GeneralLedgerAccountType>();
        }
        return this.generalLedgerAccount;
    }

    /**
     * Gets the value of the operationalMeasureIDs property.
     * 
     * @return
     *     possible object is
     *     {@link SequencedIDsType }
     *     
     */
    public SequencedIDsType getOperationalMeasureIDs() {
        return operationalMeasureIDs;
    }

    /**
     * Sets the value of the operationalMeasureIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequencedIDsType }
     *     
     */
    public void setOperationalMeasureIDs(SequencedIDsType value) {
        this.operationalMeasureIDs = value;
    }

}
