//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 04:58:29 PM CST 
//


package org.oagis.model.v101;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DebitTransferPaymentBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DebitTransferPaymentBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}TransferPaymentBaseType">
 *       &lt;sequence>
 *         &lt;element name="DebitTransferAgreement" type="{http://www.openapplications.org/oagis/10}TransferAgreementType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DebitTransferPaymentBaseType", propOrder = {
    "debitTransferAgreement"
})
@XmlSeeAlso({
    DebitTransferPaymentType.class
})
public class DebitTransferPaymentBaseType
    extends TransferPaymentBaseType
{

    @XmlElement(name = "DebitTransferAgreement")
    protected TransferAgreementType debitTransferAgreement;

    /**
     * Gets the value of the debitTransferAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link TransferAgreementType }
     *     
     */
    public TransferAgreementType getDebitTransferAgreement() {
        return debitTransferAgreement;
    }

    /**
     * Sets the value of the debitTransferAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferAgreementType }
     *     
     */
    public void setDebitTransferAgreement(TransferAgreementType value) {
        this.debitTransferAgreement = value;
    }

}
