//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:04:55 PM CST 
//


package org.oagis.model.v101;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Identifies the given portion of an organization.
 * 
 * <p>Java class for EnterpriseUnitBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnterpriseUnitBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}IdentificationType">
 *       &lt;sequence>
 *         &lt;element name="CostCenterID" type="{http://www.openapplications.org/oagis/10}IDType" minOccurs="0"/>
 *         &lt;element name="ProfitCenterID" type="{http://www.openapplications.org/oagis/10}IDType" minOccurs="0"/>
 *         &lt;element name="GLEntityID" type="{http://www.openapplications.org/oagis/10}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GeneralLedgerElement" type="{http://www.openapplications.org/oagis/10}GeneralLedgerElementType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnterpriseUnitBaseType", propOrder = {
    "costCenterID",
    "profitCenterID",
    "glEntityID",
    "generalLedgerElement"
})
@XmlSeeAlso({
    EnterpriseUnitType.class
})
public class EnterpriseUnitBaseType
    extends IdentificationType
{

    @XmlElement(name = "CostCenterID")
    protected IDType costCenterID;
    @XmlElement(name = "ProfitCenterID")
    protected IDType profitCenterID;
    @XmlElement(name = "GLEntityID")
    protected List<IDType> glEntityID;
    @XmlElement(name = "GeneralLedgerElement")
    protected GeneralLedgerElementType generalLedgerElement;

    /**
     * Gets the value of the costCenterID property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getCostCenterID() {
        return costCenterID;
    }

    /**
     * Sets the value of the costCenterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setCostCenterID(IDType value) {
        this.costCenterID = value;
    }

    /**
     * Gets the value of the profitCenterID property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getProfitCenterID() {
        return profitCenterID;
    }

    /**
     * Sets the value of the profitCenterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setProfitCenterID(IDType value) {
        this.profitCenterID = value;
    }

    /**
     * Gets the value of the glEntityID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the glEntityID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGLEntityID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getGLEntityID() {
        if (glEntityID == null) {
            glEntityID = new ArrayList<IDType>();
        }
        return this.glEntityID;
    }

    /**
     * Gets the value of the generalLedgerElement property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralLedgerElementType }
     *     
     */
    public GeneralLedgerElementType getGeneralLedgerElement() {
        return generalLedgerElement;
    }

    /**
     * Sets the value of the generalLedgerElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralLedgerElementType }
     *     
     */
    public void setGeneralLedgerElement(GeneralLedgerElementType value) {
        this.generalLedgerElement = value;
    }

}
