//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:03:55 PM CST 
//


package org.oagis.model.v101;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * TermsABIEType is logically derived from UN/CEFACT TBG17 ABIE PaymentTermsType as defined in the Reusable Aggregate Business Information Entity (RUABIE) XML Schema file.
 * 
 * <p>Java class for PaymentTermABIEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentTermABIEType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}IdentificationType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.openapplications.org/oagis/10}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EffectiveDateTime" type="{http://www.openapplications.org/oagis/10}DateTimeType" minOccurs="0"/>
 *         &lt;element name="DueDateTime" type="{http://www.openapplications.org/oagis/10}DateTimeType" minOccurs="0"/>
 *         &lt;element name="PaymentBasisCode" type="{http://www.openapplications.org/oagis/10}PaymentBasisCodeType" minOccurs="0"/>
 *         &lt;element name="Duration" type="{http://www.openapplications.org/oagis/10}DurationMeasureType" minOccurs="0"/>
 *         &lt;element name="DiscountPercent" type="{http://www.openapplications.org/oagis/10}PercentType" minOccurs="0"/>
 *         &lt;element name="SurchargePercent" type="{http://www.openapplications.org/oagis/10}PercentType" minOccurs="0"/>
 *         &lt;element name="Amount" type="{http://www.openapplications.org/oagis/10}OpenAmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentTermABIEType", propOrder = {
    "description",
    "effectiveDateTime",
    "dueDateTime",
    "paymentBasisCode",
    "duration",
    "discountPercent",
    "surchargePercent",
    "amount"
})
@XmlSeeAlso({
    PaymentTermBaseType.class
})
public class PaymentTermABIEType
    extends IdentificationType
{

    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "EffectiveDateTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String effectiveDateTime;
    @XmlElement(name = "DueDateTime")
    @XmlSchemaType(name = "anySimpleType")
    protected String dueDateTime;
    @XmlElement(name = "PaymentBasisCode")
    protected PaymentBasisCodeType paymentBasisCode;
    @XmlElement(name = "Duration")
    @XmlSchemaType(name = "anySimpleType")
    protected String duration;
    @XmlElement(name = "DiscountPercent")
    protected BigDecimal discountPercent;
    @XmlElement(name = "SurchargePercent")
    protected BigDecimal surchargePercent;
    @XmlElement(name = "Amount")
    protected OpenAmountType amount;

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the effectiveDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDateTime() {
        return effectiveDateTime;
    }

    /**
     * Sets the value of the effectiveDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDateTime(String value) {
        this.effectiveDateTime = value;
    }

    /**
     * Gets the value of the dueDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDateTime() {
        return dueDateTime;
    }

    /**
     * Sets the value of the dueDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDateTime(String value) {
        this.dueDateTime = value;
    }

    /**
     * Gets the value of the paymentBasisCode property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentBasisCodeType }
     *     
     */
    public PaymentBasisCodeType getPaymentBasisCode() {
        return paymentBasisCode;
    }

    /**
     * Sets the value of the paymentBasisCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentBasisCodeType }
     *     
     */
    public void setPaymentBasisCode(PaymentBasisCodeType value) {
        this.paymentBasisCode = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the discountPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountPercent() {
        return discountPercent;
    }

    /**
     * Sets the value of the discountPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountPercent(BigDecimal value) {
        this.discountPercent = value;
    }

    /**
     * Gets the value of the surchargePercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSurchargePercent() {
        return surchargePercent;
    }

    /**
     * Sets the value of the surchargePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSurchargePercent(BigDecimal value) {
        this.surchargePercent = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link OpenAmountType }
     *     
     */
    public OpenAmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenAmountType }
     *     
     */
    public void setAmount(OpenAmountType value) {
        this.amount = value;
    }

}
