//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:01:47 PM CST 
//


package org.oagis.model.v101;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This identifies discrepancy information for the receipt.
 * 
 * The typeCode identifies the type of discrepancy. 
 * 
 * The ReasonCode Identifies the reason for the discrepancy.
 * 
 * If the discrepancy applies to specific quantities of the item, then the quantity can be specified. If no quantity is specified, the discrepancy applies to the inventory occurence as a whole
 * 
 * <p>Java class for ReceiveDeliveryDiscrepancyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReceiveDeliveryDiscrepancyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}ReceiveDeliveryDiscrepancyBaseType">
 *       &lt;sequence>
 *         &lt;element name="Extension" type="{http://www.openapplications.org/oagis/10}ReceiveDeliveryDiscrepancyExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReceiveDeliveryDiscrepancyType", propOrder = {
    "extension"
})
public class ReceiveDeliveryDiscrepancyType
    extends ReceiveDeliveryDiscrepancyBaseType
{

    @XmlElement(name = "Extension")
    protected List<ReceiveDeliveryDiscrepancyExtensionType> extension;

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReceiveDeliveryDiscrepancyExtensionType }
     * 
     * 
     */
    public List<ReceiveDeliveryDiscrepancyExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ReceiveDeliveryDiscrepancyExtensionType>();
        }
        return this.extension;
    }

}
