//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 04:59:42 PM CST 
//


package org.oagis.model.v101;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RootCauseBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RootCauseBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}IdentificationType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.openapplications.org/oagis/10}FreeFormTextGroup"/>
 *         &lt;group ref="{http://www.openapplications.org/oagis/10}ReferencesGroup"/>
 *         &lt;element name="Classification" type="{http://www.openapplications.org/oagis/10}ClassificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Symptom" type="{http://www.openapplications.org/oagis/10}SymptomType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Cause" type="{http://www.openapplications.org/oagis/10}CauseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Defect" type="{http://www.openapplications.org/oagis/10}DefectType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResponsibleProcess" type="{http://www.openapplications.org/oagis/10}ResponsibleProcessType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResponsibleFacility" type="{http://www.openapplications.org/oagis/10}FacilityType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResponsibleComponentInstance" type="{http://www.openapplications.org/oagis/10}ComponentInstanceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResponsibleSupplier" type="{http://www.openapplications.org/oagis/10}SupplierPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResponsibleMachine" type="{http://www.openapplications.org/oagis/10}MachineType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RootCauseBaseType", propOrder = {
    "description",
    "note",
    "documentReference",
    "attachment",
    "classification",
    "symptom",
    "cause",
    "defect",
    "responsibleProcess",
    "responsibleFacility",
    "responsibleComponentInstance",
    "responsibleSupplier",
    "responsibleMachine"
})
@XmlSeeAlso({
    RootCauseType.class
})
public class RootCauseBaseType
    extends IdentificationType
{

    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "Note")
    protected List<NoteType> note;
    @XmlElement(name = "DocumentReference")
    protected List<DocumentReferenceType> documentReference;
    @XmlElement(name = "Attachment")
    protected List<AttachmentType> attachment;
    @XmlElement(name = "Classification")
    protected List<ClassificationType> classification;
    @XmlElement(name = "Symptom")
    protected List<SymptomType> symptom;
    @XmlElement(name = "Cause")
    protected List<CauseType> cause;
    @XmlElement(name = "Defect")
    protected List<DefectType> defect;
    @XmlElement(name = "ResponsibleProcess")
    protected List<ResponsibleProcessType> responsibleProcess;
    @XmlElement(name = "ResponsibleFacility")
    protected List<FacilityType> responsibleFacility;
    @XmlElement(name = "ResponsibleComponentInstance")
    protected List<ComponentInstanceType> responsibleComponentInstance;
    @XmlElement(name = "ResponsibleSupplier")
    protected List<SupplierPartyType> responsibleSupplier;
    @XmlElement(name = "ResponsibleMachine")
    protected List<MachineType> responsibleMachine;

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoteType }
     * 
     * 
     */
    public List<NoteType> getNote() {
        if (note == null) {
            note = new ArrayList<NoteType>();
        }
        return this.note;
    }

    /**
     * Gets the value of the documentReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentReferenceType }
     * 
     * 
     */
    public List<DocumentReferenceType> getDocumentReference() {
        if (documentReference == null) {
            documentReference = new ArrayList<DocumentReferenceType>();
        }
        return this.documentReference;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentType }
     * 
     * 
     */
    public List<AttachmentType> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<AttachmentType>();
        }
        return this.attachment;
    }

    /**
     * Gets the value of the classification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassificationType }
     * 
     * 
     */
    public List<ClassificationType> getClassification() {
        if (classification == null) {
            classification = new ArrayList<ClassificationType>();
        }
        return this.classification;
    }

    /**
     * Gets the value of the symptom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the symptom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSymptom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SymptomType }
     * 
     * 
     */
    public List<SymptomType> getSymptom() {
        if (symptom == null) {
            symptom = new ArrayList<SymptomType>();
        }
        return this.symptom;
    }

    /**
     * Gets the value of the cause property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cause property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCause().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CauseType }
     * 
     * 
     */
    public List<CauseType> getCause() {
        if (cause == null) {
            cause = new ArrayList<CauseType>();
        }
        return this.cause;
    }

    /**
     * Gets the value of the defect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefectType }
     * 
     * 
     */
    public List<DefectType> getDefect() {
        if (defect == null) {
            defect = new ArrayList<DefectType>();
        }
        return this.defect;
    }

    /**
     * Gets the value of the responsibleProcess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responsibleProcess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponsibleProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponsibleProcessType }
     * 
     * 
     */
    public List<ResponsibleProcessType> getResponsibleProcess() {
        if (responsibleProcess == null) {
            responsibleProcess = new ArrayList<ResponsibleProcessType>();
        }
        return this.responsibleProcess;
    }

    /**
     * Gets the value of the responsibleFacility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responsibleFacility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponsibleFacility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FacilityType }
     * 
     * 
     */
    public List<FacilityType> getResponsibleFacility() {
        if (responsibleFacility == null) {
            responsibleFacility = new ArrayList<FacilityType>();
        }
        return this.responsibleFacility;
    }

    /**
     * Gets the value of the responsibleComponentInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responsibleComponentInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponsibleComponentInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComponentInstanceType }
     * 
     * 
     */
    public List<ComponentInstanceType> getResponsibleComponentInstance() {
        if (responsibleComponentInstance == null) {
            responsibleComponentInstance = new ArrayList<ComponentInstanceType>();
        }
        return this.responsibleComponentInstance;
    }

    /**
     * Gets the value of the responsibleSupplier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responsibleSupplier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponsibleSupplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplierPartyType }
     * 
     * 
     */
    public List<SupplierPartyType> getResponsibleSupplier() {
        if (responsibleSupplier == null) {
            responsibleSupplier = new ArrayList<SupplierPartyType>();
        }
        return this.responsibleSupplier;
    }

    /**
     * Gets the value of the responsibleMachine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responsibleMachine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponsibleMachine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MachineType }
     * 
     * 
     */
    public List<MachineType> getResponsibleMachine() {
        if (responsibleMachine == null) {
            responsibleMachine = new ArrayList<MachineType>();
        }
        return this.responsibleMachine;
    }

}
