//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:04:46 PM CST 
//


package org.oagis.model.v101;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WarehouseCarrierBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WarehouseCarrierBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.openapplications.org/oagis/10}IdentificationType">
 *       &lt;sequence>
 *         &lt;element name="ShipmentMethodOfPaymentCode" type="{http://www.openapplications.org/oagis/10}CodeType" minOccurs="0"/>
 *         &lt;element name="TransportationTypeCode" type="{http://www.openapplications.org/oagis/10}CodeType" minOccurs="0"/>
 *         &lt;element name="PalletExchangeCode" type="{http://www.openapplications.org/oagis/10}CodeType" minOccurs="0"/>
 *         &lt;element name="RoutingCarrierName" type="{http://www.openapplications.org/oagis/10}NameType" minOccurs="0"/>
 *         &lt;element name="SCACID" type="{http://www.openapplications.org/oagis/10}IDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WarehouseCarrierBaseType", propOrder = {
    "shipmentMethodOfPaymentCode",
    "transportationTypeCode",
    "palletExchangeCode",
    "routingCarrierName",
    "scacid"
})
@XmlSeeAlso({
    WarehouseCarrierType.class
})
public class WarehouseCarrierBaseType
    extends IdentificationType
{

    @XmlElement(name = "ShipmentMethodOfPaymentCode")
    protected CodeType shipmentMethodOfPaymentCode;
    @XmlElement(name = "TransportationTypeCode")
    protected CodeType transportationTypeCode;
    @XmlElement(name = "PalletExchangeCode")
    protected CodeType palletExchangeCode;
    @XmlElement(name = "RoutingCarrierName")
    protected NameType routingCarrierName;
    @XmlElement(name = "SCACID")
    protected IDType scacid;

    /**
     * Gets the value of the shipmentMethodOfPaymentCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getShipmentMethodOfPaymentCode() {
        return shipmentMethodOfPaymentCode;
    }

    /**
     * Sets the value of the shipmentMethodOfPaymentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setShipmentMethodOfPaymentCode(CodeType value) {
        this.shipmentMethodOfPaymentCode = value;
    }

    /**
     * Gets the value of the transportationTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getTransportationTypeCode() {
        return transportationTypeCode;
    }

    /**
     * Sets the value of the transportationTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setTransportationTypeCode(CodeType value) {
        this.transportationTypeCode = value;
    }

    /**
     * Gets the value of the palletExchangeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getPalletExchangeCode() {
        return palletExchangeCode;
    }

    /**
     * Sets the value of the palletExchangeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setPalletExchangeCode(CodeType value) {
        this.palletExchangeCode = value;
    }

    /**
     * Gets the value of the routingCarrierName property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getRoutingCarrierName() {
        return routingCarrierName;
    }

    /**
     * Sets the value of the routingCarrierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setRoutingCarrierName(NameType value) {
        this.routingCarrierName = value;
    }

    /**
     * Gets the value of the scacid property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getSCACID() {
        return scacid;
    }

    /**
     * Sets the value of the scacid property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setSCACID(IDType value) {
        this.scacid = value;
    }

}
